name: "Deployment Action"
description: "Creates a GitHub Deployment"
author: "chrnorm"
branding:
  icon: arrow-up
  color: black
inputs:
  initial_status:
    description: "Initial status for the deployment"
    default: "pending"
  token:
    description: "Github repository token"
  target_url:
    description: "Target url location"
  ref:
    description: "Ref from where the deployment originates from"
  description:
    description: "Descriptive message about the deployment"
  environment:
    description: "The name of the environment for the deployment"
    default: "production"
  
outputs:
  deployment_id:
    description: "The ID of the created deployment"
runs:
  using: "node12"
  main: "lib/main.js"
